CREATE DATABASE waste_management_system;
USE waste_management_system;

CREATE TABLE Zone (
    ZoneID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    GeographicBoundary VARCHAR(255) NOT NULL
);

CREATE TABLE Route (
    RouteID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    RouteDetails TEXT NOT NULL,
    ZoneID INT NOT NULL,
    FOREIGN KEY (ZoneID) REFERENCES Zone(ZoneID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE CollectionSchedule (
    ScheduleID INT PRIMARY KEY AUTO_INCREMENT,
    RouteID INT NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    IsRecurring BOOLEAN NOT NULL DEFAULT TRUE,
    ScheduledDate DATE NOT NULL,
    CollectionDay VARCHAR(20) NOT NULL,
    FOREIGN KEY (RouteID) REFERENCES Route(RouteID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Household (
    HouseholdID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    ContactEmail VARCHAR(100) NOT NULL,
    RouteID INT NOT NULL,
    FOREIGN KEY (RouteID) REFERENCES Route(RouteID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE WasteType (
    WasteTypeID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    DisposalMethod VARCHAR(100) NOT NULL,
    ProcessingCost DECIMAL(10, 2) NOT NULL
);

CREATE TABLE WasteBin (
    BinID INT PRIMARY KEY AUTO_INCREMENT,
    HouseholdID INT NOT NULL,
    WasteTypeID INT NOT NULL,
    BinLocation VARCHAR(100) NOT NULL,
    Capacity DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (HouseholdID) REFERENCES Household(HouseholdID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (WasteTypeID) REFERENCES WasteType(WasteTypeID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Staff (
    StaffID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    HireDate DATE NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Department VARCHAR(50),
    ContactPhone VARCHAR(20)
);

CREATE TABLE Vehicle (
    VehicleID INT PRIMARY KEY AUTO_INCREMENT,
    Model VARCHAR(50) NOT NULL,
    Make VARCHAR(50) NOT NULL,
    Capacity DECIMAL(10, 2) NOT NULL,
    LicensePlate VARCHAR(20) NOT NULL UNIQUE,
    Status VARCHAR(20) NOT NULL DEFAULT 'Active'
);

CREATE TABLE CollectionLog (
    CollectionLogID INT PRIMARY KEY AUTO_INCREMENT,
    RouteID INT NOT NULL,
    VehicleID INT NOT NULL,
    CollectionDate DATE NOT NULL,
    TotalRouteWeight DECIMAL(10, 2),
    Status VARCHAR(20) NOT NULL DEFAULT 'Completed',
    FOREIGN KEY (RouteID) REFERENCES Route(RouteID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RecyclingCenter (
    CenterID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    ProcessingCapacity DECIMAL(10, 2) NOT NULL
);

CREATE TABLE LogStaff (
    CollectionLogID INT NOT NULL,
    StaffID INT NOT NULL,
    Role VARCHAR(50) NOT NULL,
    PRIMARY KEY (CollectionLogID, StaffID),
    FOREIGN KEY (CollectionLogID) REFERENCES CollectionLog(CollectionLogID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LogVehicle (
    CollectionLogID INT NOT NULL,
    VehicleID INT NOT NULL,
    DriverStaffID INT,
    PRIMARY KEY (CollectionLogID, VehicleID),
    FOREIGN KEY (CollectionLogID) REFERENCES CollectionLog(CollectionLogID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (DriverStaffID) REFERENCES Staff(StaffID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE CollectionDetails (
    CollectionLogID INT NOT NULL,
    WasteBinID INT NOT NULL,
    WasteTypeID INT NOT NULL,
    CollectedWeight DECIMAL(10, 2) NOT NULL,
    CollectionTime TIME NOT NULL,
    PRIMARY KEY (CollectionLogID, WasteBinID),
    FOREIGN KEY (CollectionLogID) REFERENCES CollectionLog(CollectionLogID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (WasteBinID) REFERENCES WasteBin(BinID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (WasteTypeID) REFERENCES WasteType(WasteTypeID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CenterProcessing (
    CenterID INT NOT NULL,
    WasteTypeID INT NOT NULL,
    ProcessingCost DECIMAL(10, 2) NOT NULL,
    ProcessingCapacity DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (CenterID, WasteTypeID),
    FOREIGN KEY (CenterID) REFERENCES RecyclingCenter(CenterID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (WasteTypeID) REFERENCES WasteType(WasteTypeID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Violation (
    ViolationID INT PRIMARY KEY AUTO_INCREMENT,
    HouseholdID INT NOT NULL,
    DateIssued DATE NOT NULL,
    Reason VARCHAR(255) NOT NULL,
    FineAmount DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    ViolationType VARCHAR(50) NOT NULL,
    FOREIGN KEY (HouseholdID) REFERENCES Household(HouseholdID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE Payment (
    PaymentID INT PRIMARY KEY AUTO_INCREMENT,
    HouseholdID INT NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    PaymentDate DATE NOT NULL,
    PaymentType VARCHAR(50) NOT NULL,
    ServicePeriod VARCHAR(50),
    ViolationID INT,
    FOREIGN KEY (HouseholdID) REFERENCES Household(HouseholdID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ViolationID) REFERENCES Violation(ViolationID) ON DELETE SET NULL ON UPDATE CASCADE
);